Repository DeveloperAcademy-POSTECH/2024-MC3-A16-PalangPalang, pull requests merged in 2024-08, with the labels that each got.

#8 [Chore] 깃템플릿, 깃이그노어 업로드
  .github/ISSUE_TEMPLATE/기능-이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: Rules

#9 [👾Chore] #2 Tuist Settings
  PalangPalang/Project.swift
  Plugins/PalangPalang/Package.swift
  Plugins/PalangPalang/Plugin.swift
  Plugins/PalangPalang/ProjectDescriptionHelpers/LocalHelper.swift
  Plugins/PalangPalang/Sources/tuist-my-cli/main.swift
  Tuist/Config.swift
  Tuist/ProjectDescriptionHelpers/Environment.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Workspace.swift
Labels: Setting

#10 [Settings⚙️] #3 아키텍처 기본 구성 및 핵심 Alarm 로직 구성
  PalangPalang/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Contents.json
  PalangPalang/Resources/InfoPlists/PalangPalang-Info.plist
  PalangPalang/Resources/InfoPlists/PalangPalangTests-Info.plist
  PalangPalang/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  PalangPalang/Sources/App/AppDelegate.swift
  PalangPalang/Sources/App/AppView.swift
  PalangPalang/Sources/Data/Services/DataStoreService.swift
  PalangPalang/Sources/Data/Services/LocalNotificationService.swift
  PalangPalang/Sources/Data/Services/TimerSchedulerService.swift
  PalangPalang/Sources/Domain/Model/AlarmModel.swift
  PalangPalang/Sources/Domain/Model/AlarmSettingsModel.swift
  PalangPalang/Sources/Domain/Model/AlarmState.swift
  PalangPalang/Sources/Domain/Model/PropertyWrapper/ValidHour.swift
  PalangPalang/Sources/Domain/Model/PropertyWrapper/ValidMinutes.swift
  PalangPalang/Sources/Domain/Model/Storable.swift
  PalangPalang/Sources/Domain/UseCase/AlarmUseCase.swift
  PalangPalang/Sources/Presenters/Scenes/Alarm/AlarmOnProcessView.swift
  PalangPalang/Sources/Presenters/Scenes/Mission/MissionCompletedView.swift
  PalangPalang/Sources/Presenters/Scenes/Mission/MissionOnProcessView.swift
  PalangPalang/Sources/Presenters/Scenes/Mission/MissionTimeoutView.swift
  PalangPalang/Sources/Presenters/Scenes/Settings/AlarmMain.swift
  PalangPalang/Sources/Presenters/Scenes/Settings/AlarmMainView.swift
  PalangPalang/Sources/Presenters/Scenes/Settings/AlarmOnSettings.swift
  PalangPalang/Sources/Presenters/ViewModel/AlarmViewModel.swift
  PalangPalang/Sources/Presenters/ViewModel/MissionViewModel.swift
  PalangPalang/Sources/Presenters/ViewModel/SettingsViewModel.swift
  PalangPalang/Tests/PalangPalangTests.swift
Labels: Setting

#11 [📚Docs] #3 DesingSystem, Utils 분류생성
  Config.zip
  PalangPalang/Sources/DesignSystem/Extensions/Font+PalangFont.swift
  PalangPalang/Sources/Utils/Extensions/empty.swift
  PalangPalang/Sources/Utils/empty.swift
Labels: Setting

#13 [🔥HOTFIX] #12 Alarm 기능
  PalangPalang/Sources/Data/Services/TimerSchedulerService.swift
  PalangPalang/Sources/Domain/Model/AlarmModel.swift
  PalangPalang/Sources/Domain/UseCase/AlarmUseCase.swift
  PalangPalang/Sources/Utils/empty123.swift
Labels: HOTFIX

#14 [✏️Comment] #1-프로젝트 전반에 사용되는 시점, 및 화면 명칭 통일
  PalangPalang/Sources/App/AppView.swift
  PalangPalang/Sources/Domain/Model/AlarmSettingsModel.swift
  PalangPalang/Sources/Domain/Model/AlarmState.swift
  PalangPalang/Sources/Domain/UseCase/AlarmUseCase.swift
  PalangPalang/Sources/Domain/UseCase/Interface/AlarmOnProcess.swift
  PalangPalang/Sources/Domain/UseCase/Interface/AlarmStaus.swift
  PalangPalang/Sources/Domain/UseCase/Interface/MainAlarmSettings.swift
  PalangPalang/Sources/Domain/UseCase/Interface/MissionOnProcess.swift
  PalangPalang/Sources/Presenters/Scenes/AlarmOnProcess/AlarmOnProcessView.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmMain.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmMainView.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmOnSettings.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionCompletedView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionOnProcessView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionTimeoutView.swift
  PalangPalang/Sources/Presenters/ViewModel/AlarmOnProcessViewModel.swift
  PalangPalang/Sources/Presenters/ViewModel/AlarmSettingsViewModel.swift
  PalangPalang/Sources/Presenters/ViewModel/MissionOnProcessViewModel.swift
Labels: Comment

#15 [💄View]#1- Font, Color 디자인스타일 설정
  PalangPalang/Resources/Assets.xcassets/Colors/Button/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Button/Text00.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Button/Text01.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Button/Text02.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Button/Text03.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Primary/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Primary/Gray.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Primary/White.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Primary/Yellow.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Secondary/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Secondary/Gray01.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Secondary/Gray02.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Secondary/Yellow01.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Text/Button01.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Text/Button02.colorset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Colors/Text/Contents.json
  PalangPalang/Resources/Font/Pretendard-Bold.otf
  PalangPalang/Resources/Font/Pretendard-Medium.otf
  PalangPalang/Resources/Font/Ubuntu-Bold.ttf
  PalangPalang/Resources/Font/Ubuntu-Medium.ttf
  PalangPalang/Resources/InfoPlists/PalangPalang-Info.plist
  PalangPalang/Sources/DesignSystem/Extensions/Font+PalangFont.swift
  PalangPalang/Sources/DesignSystem/Extensions/ShapeStyle+PalangColor.swift
  PalangPalang/Sources/DesignSystem/Extensions/View+PalangFont.swift
Labels: View

#17 [✨Feat] #16 Alarm 기능 및 앱 전체 로직 구현 완료
  PalangPalang/Resources/Assets.xcassets/Images/CancealAlarmButton.imageset/CancealAlarmButton.png
  PalangPalang/Resources/Assets.xcassets/Images/CancealAlarmButton.imageset/CancealAlarmButton@2x.png
  PalangPalang/Resources/Assets.xcassets/Images/CancealAlarmButton.imageset/CancealAlarmButton@3x.png
  PalangPalang/Resources/Assets.xcassets/Images/CancealAlarmButton.imageset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar1.imageset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar1.imageset/ProgressBar1.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar1.imageset/ProgressBar1@2x.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar1.imageset/ProgressBar1@3x.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar2.imageset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar2.imageset/ProgressBar2.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar2.imageset/ProgressBar2@2x.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar2.imageset/ProgressBar2@3x.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar3.imageset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar3.imageset/ProgressBar3.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar3.imageset/ProgressBar3@2x.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar3.imageset/ProgressBar3@3x.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar4.imageset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar4.imageset/ProgressBar4.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar4.imageset/ProgressBar4@2x.png
  PalangPalang/Resources/Assets.xcassets/Images/ProgressBar4.imageset/ProgressBar4@3x.png
  PalangPalang/Sources/App/AppDelegate.swift
  PalangPalang/Sources/App/AppView.swift
  PalangPalang/Sources/Domain/Model/AlarmModel.swift
  PalangPalang/Sources/Domain/Model/AlarmSettingsModel.swift
  PalangPalang/Sources/Domain/Model/AlarmState.swift
  PalangPalang/Sources/Domain/Model/MissionModel.swift
  PalangPalang/Sources/Domain/Model/PropertyWrapper/ValidMinutesOrSecond.swift
  PalangPalang/Sources/Domain/UseCase/AlarmUseCase.swift
  PalangPalang/Sources/Domain/UseCase/Interface/AlarmOnProcess.swift
  PalangPalang/Sources/Domain/UseCase/Interface/MissionCompleted.swift
  PalangPalang/Sources/Domain/UseCase/Interface/MissionOnProcess.swift
  PalangPalang/Sources/Presenters/Scenes/AlarmOnProcess/AlarmOnProcessView.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmMain.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmMainView.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmOnSettings.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionCompletedView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionOnProcessView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionTimeoutView.swift
  PalangPalang/Sources/Presenters/ViewModel/AlarmOnProcessViewModel.swift
  PalangPalang/Sources/Presenters/ViewModel/AlarmSettingsViewModel.swift
  PalangPalang/Sources/Presenters/ViewModel/MissionOnProcessViewModel.swift
  PalangPalang/Sources/Utils/Extensions/Date+GetTime.swift
  PalangPalang/Sources/Utils/Extensions/empty.swift
  PalangPalang/Sources/Utils/empty123.swift
Labels: Feature

#21 [🔥HOTFIX] #20 포어그라운드 상태에 들어섰을 때 초 상태 미갱신 문제 해결
  PalangPalang/Sources/Presenters/ViewModel/AlarmOnProcessViewModel.swift
Labels: HOTFIX

#19 [🎨Assets] #18 앱 로고 및 라이트 모드 고정
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/120*120.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/152*152.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/167*167.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/180*180.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/29*29.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/40*40.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/58*58 1.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/58*58.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/76*76.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/80*80 1.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/80*80.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 52.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 70.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 71.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 72.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 73.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 74.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 75.png
  PalangPalang/Resources/InfoPlists/PalangPalang-Info.plist
Labels: View

#27 [✨Feat] #26 가속도로 발걸음 수 감소 로직 완성
  PalangPalang/Sources/Domain/Model/MissionCompletedModel.swift
  PalangPalang/Sources/Domain/UseCase/AlarmUseCase.swift
  PalangPalang/Sources/Presenters/Scenes/AlarmOnProcess/AlarmOnProcessView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionOnProcessView.swift
  PalangPalang/Sources/Presenters/ViewModel/MissionOnProcessViewModel.swift
Labels: Feature

#32 [💄View]#31- 성공화면, 실패화면 생성 및 Rottie 연동
  PalangPalang/Project.swift
  PalangPalang/Resources/Assets.xcassets/Images/FinalGhostLeading.imageset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/FinalGhostLeading.imageset/FinalGhostLeading.png
  PalangPalang/Resources/Assets.xcassets/Images/FinalGhostLeading.imageset/FinalGhostLeading@2x.png
  PalangPalang/Resources/Assets.xcassets/Images/FinalGhostLeading.imageset/FinalGhostLeading@3x.png
  PalangPalang/Resources/Assets.xcassets/Images/FinalGhostTrailing.imageset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/FinalGhostTrailing.imageset/FinalGhostTrailing.png
  PalangPalang/Resources/Assets.xcassets/Images/FinalGhostTrailing.imageset/FinalGhostTrailing@2x.png
  PalangPalang/Resources/Assets.xcassets/Images/FinalGhostTrailing.imageset/FinalGhostTrailing@3x.png
  PalangPalang/Resources/Assets.xcassets/Images/GhostClosedEyes.imageset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/GhostClosedEyes.imageset/GhostClosedEyes.png
  PalangPalang/Resources/Assets.xcassets/Images/GhostClosedEyes.imageset/GhostClosedEyes@2x.png
  PalangPalang/Resources/Assets.xcassets/Images/GhostClosedEyes.imageset/GhostClosedEyes@3x.png
  PalangPalang/Resources/Assets.xcassets/Images/GhostOpenEyes.imageset/Contents.json
  PalangPalang/Resources/Assets.xcassets/Images/GhostOpenEyes.imageset/GhostOpenEyes.png
  PalangPalang/Resources/Assets.xcassets/Images/GhostOpenEyes.imageset/GhostOpenEyes@2x.png
  PalangPalang/Resources/Assets.xcassets/Images/GhostOpenEyes.imageset/GhostOpenEyes@3x.png
  PalangPalang/Resources/Rottie/GetGhost.json
  PalangPalang/Sources/Domain/Model/MissionCompletedModel.swift
  PalangPalang/Sources/Domain/UseCase/AlarmUseCase.swift
  PalangPalang/Sources/Domain/UseCase/Interface/MissionCompleted.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/LottieGhost.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionCompletedView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionTimeoutView.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Feature

#35 [🔨Refactor] #28 디리니를 위한 귀신 추가 로직 리팩토링
  PalangPalang/Sources/Domain/Model/Extension/Int+Storable.swift
  PalangPalang/Sources/Domain/Model/GhostModel.swift
  PalangPalang/Sources/Domain/UseCase/AlarmUseCase.swift
  PalangPalang/Sources/Domain/UseCase/Interface/ReadMissionCount.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmMain.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmMainView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionOnProcessView.swift
  PalangPalang/Sources/Presenters/ViewModel/GhostViewModel.swift
Labels: Refactor

#36 [✏️Comment] 사소한 코드 수정 및 코드 위치 변경
  PalangPalang/Sources/App/AppView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionCompletedView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionTimeoutView.swift
Labels: Refactor

#34 [💄View]CustomPicker만들기 및 가독성 이슈 수정! #33
  PalangPalang/Sources/DesignSystem/Extensions/ShapeStyle+PalangColor.swift
  PalangPalang/Sources/DesignSystem/Extensions/View+PalangFont.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmMain.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmOnSettings.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/CustomPicker.swift
Labels: View

#37 [🔨Refactor] 화면 상하 간격 수정
  PalangPalang/Sources/Domain/Model/MissionCompletedModel.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionCompletedView.swift
  PalangPalang/Sources/Presenters/Scenes/MissionOnProcess/MissionTimeoutView.swift
Labels: View, Refactor

#39 [v0.1] 최초 UT 버전
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/120*120.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/152*152.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/167*167.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/180*180.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/29*29.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/40*40.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/58*58 1.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/58*58.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/76*76.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/80*80 1.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/80*80.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 52.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 70.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 71.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 72.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 73.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 74.png
  PalangPalang/Resources/Assets.xcassets/AppIcon.appiconset/Frame 75.png
  PalangPalang/Resources/InfoPlists/PalangPalang-Info.plist
  PalangPalang/Sources/Domain/UseCase/AlarmUseCase.swift
  PalangPalang/Sources/Presenters/Scenes/MainAlarmSettings/AlarmMain.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Version
